/*
 * Style reminder: the About page is grounded, local, and transparent—Indian
 * workshop character without inventing history, ratings, or certifications.
 */
import { ArrowUpRight, Check, CarFront, ShieldCheck, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Breadcrumb, CalloutStrip, PageIntro, SectionLabel } from "@/components/SiteChrome";
import { assets, values } from "@/lib/siteData";

export default function About() {
  return <div className="page-shell"><PageIntro number="02" eyebrow="The workshop behind the care" title="Local hands." accent="serious care." lead="Shree Sanwaliya Car Detailing & Service brings washing, detailing, polishing, and workshop support together for cars and pickups in Dadi, Rajasthan." image={assets.mechanical} /><section className="content-section about-story"><div className="shell-width"><Breadcrumb label="About the workshop" /><div className="about-story-grid"><div><SectionLabel number="01" eyebrow="The Sanwaliya way" /><h2>Care should feel<br /><em>straightforward.</em></h2></div><div><p className="detail-lead">Your car does not need a complicated story. It needs a workshop that looks carefully, explains the next step, and treats the finish like it matters.</p><p className="body-copy">That is the role of Shree Sanwaliya: a practical local service point for foam washing, deep cleaning, dry cleaning, light buffing, rubbing, polishing, and mechanical work. The website uses English to make the service menu easy to understand, while the visual language stays rooted in the black-and-gold identity of the supplied workshop poster.</p><Link className="text-link text-link--dark" href="/services"><span>Explore the service menu</span><ArrowUpRight size={16} /></Link></div></div></div></section><section className="content-section values-section"><div className="shell-width values-grid"><div className="values-image"><img src={assets.interior} alt="Indian vehicle interior being carefully deep cleaned" /><div><span>Local care / 03</span><strong>Built for<br />the road here.</strong></div></div><div className="values-copy"><SectionLabel number="02" eyebrow="What guides the work" /><h2>Practical first.<br /><span>Finish always.</span></h2><div className="values-list">{values.map((value) => { const Icon = value.icon; return <div key={value.number}><span className="value-number">{value.number}</span><span className="value-icon"><Icon size={18} /></span><div><h3>{value.title}</h3><p>{value.copy}</p></div></div>; })}</div></div></div></section><section className="content-section guardrail-section"><div className="shell-width guardrail-grid"><div><SectionLabel number="03" eyebrow="A clear promise" /><h2>No inflated<br /><em>claims.</em></h2></div><div className="guardrail-card"><ShieldCheck size={26} /><p>We keep the website focused on confirmed services, a direct phone line, and a clear location. Prices, timings, specific mechanical jobs, and customer reviews should be discussed or confirmed with the workshop.</p><div><Check size={14} />Clear information</div><div><Check size={14} />Direct conversation</div><div><Check size={14} />Care for cars + pickups</div></div></div></section><CalloutStrip title="Start with a conversation about your vehicle." /></div>;
}
