/*
 * Style reminder: mobile-first Indian workshop editorial—tactile images, gold
 * service routes, generous tap targets, and floating motion that stays useful.
 */
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, MapPin, MessageCircle, PhoneCall, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { MapView } from "@/components/Map";
import { CalloutStrip, SectionLabel } from "@/components/SiteChrome";
import { address, assets, location, mapEmbedUrl, mapUrl, phone, serviceGroups, values } from "@/lib/siteData";

export default function Home() {
  return <div className="home-page">
    <section className="home-hero" aria-labelledby="hero-title">
      <img className="home-hero-image" src={assets.hero} alt="Indian SUV being washed in a warm workshop bay" />
      <div className="home-hero-shade" />
      <div className="home-hero-route home-hero-route--one" /><div className="home-hero-route home-hero-route--two" />
      <div className="shell-width home-hero-inner">
        <div className="home-hero-copy">
          <div className="eyebrow reveal reveal--delay-1"><span className="eyebrow-dot" /> Indian car care · Motipura, Bundi</div>
          <h1 id="hero-title" className="home-hero-title reveal reveal--delay-2">Your drive<br /><em>deserves</em><br />a clean start.</h1>
          <p className="home-hero-lead reveal reveal--delay-3">Washing, cleaning, polishing, detailing, and workshop care for cars and pickups—kept clear, practical, and close to the road.</p>
          <div className="home-hero-actions reveal reveal--delay-4"><Link className="button button--gold" href="/services">Explore services <ArrowDownRight size={17} /></Link><a className="text-link" href={`tel:${phone}`}><span>Talk to the team</span><ArrowUpRight size={16} /></a></div>
        </div>
        <div className="home-hero-note reveal reveal--delay-4"><div><span>01</span><strong>Shree Sanwaliya</strong></div><p>SH34 / SH37A<br />Motipura, Loharpura<br />Bundi, Rajasthan</p></div>
      </div>
      <div className="shell-width home-hero-bottom"><span>|| Jai Shri Sanwaliya Seth ||</span><strong>Your car’s care, our responsibility.</strong><span className="scroll-cue">Scroll <ChevronDown size={16} /></span></div>
    </section>

    <section className="home-intro"><div className="shell-width home-intro-grid"><div><SectionLabel number="01" eyebrow="A local workshop, clearly presented" /><p className="side-note">One place for the clean, the shine, and the next practical workshop job.</p></div><div><h2>Care that starts<br /><span>with a look.</span></h2><p className="body-copy">Every car brings a different road story. Start with the service you have in mind, bring the vehicle to the bay, and talk through what it needs next.</p><div className="home-proof-row">{values.map((value) => <div key={value.number}><strong>{value.number}</strong><span>{value.title}</span></div>)}</div></div></div></section>

    <section className="home-route-section"><div className="shell-width"><div className="section-heading section-heading--split"><div><SectionLabel number="02" eyebrow="Choose a care route" /><h2>Three routes.<br /><em>One clear start.</em></h2></div><Link className="text-link" href="/services"><span>See every service</span><ArrowUpRight size={16} /></Link></div><div className="home-route-grid">{serviceGroups.map((group) => { const Icon = group.icon; return <Link href={`/services/${group.slug}`} className="home-route-card" key={group.slug}><div className={`home-route-media home-route-media--${group.slug}`}><img src={group.image} alt={`${group.title} service in an Indian workshop`} /><span>{group.number}</span><Icon size={20} /></div><div className="home-route-copy"><small>{group.eyebrow}</small><h3>{group.title}</h3><p>{group.summary}</p><span className="route-link">Open route <ArrowUpRight size={16} /></span></div></Link>; })}</div></div></section>

    <section className="home-standard"><div className="home-standard-glow" /><div className="shell-width home-standard-grid"><div className="home-standard-image"><img src={assets.polish} alt="Founder polishing a vehicle in an Indian detailing bay" /><span>Finish / 02</span></div><div><SectionLabel number="03" eyebrow="The Sanwaliya standard" /><h2>Good work is<br /><em>felt</em> before it’s seen.</h2><p className="body-copy">The careful rinse. The clean edge around a badge. The moment paint catches light again. Our job is to treat your vehicle with attention before it leaves the bay.</p><div className="check-list"><div><span><Check size={14} /></span><p><strong>Clear, practical service</strong><br />No complicated package language.</p></div><div><span><Check size={14} /></span><p><strong>Cars and pickups</strong><br />Care for the vehicles that keep your day moving.</p></div><div><span><Check size={14} /></span><p><strong>One direct conversation</strong><br />Tell us what you want looked after.</p></div></div><Link className="button button--outline" href="/about">See the workshop standard <ArrowUpRight size={16} /></Link></div></div></section>

    <section className="home-founder"><div className="shell-width home-founder-grid"><div className="home-founder-image"><img src={assets.founderOffice} alt="Founder of Shree Sanwaliya Car Detailing & Service in a professional office setup" /><span>Founder-led care / 04</span></div><div className="home-founder-copy"><SectionLabel number="04" eyebrow="Meet the founder" /><h2>The care<br /><span>has a face.</span></h2><p className="detail-lead">A direct, founder-led conversation sits behind every service route.</p><p className="body-copy">The founder of Shree Sanwaliya brings the workshop close to the vehicle: look carefully, speak plainly about the next step, and keep the work connected to the roads, dust, and daily drives of Rajasthan.</p><div className="home-founder-signoff"><strong>Shree Sanwaliya</strong><span>Founder · Car Detailing &amp; Service</span></div><Link className="button button--outline" href="/about">Read the founder story <ArrowUpRight size={16} /></Link></div></div></section>

    <section className="home-india"><div className="shell-width home-india-grid"><div><SectionLabel number="05" eyebrow="Made for the road here" /><h2>Dust, distance,<br /><span>daily drives.</span></h2><p className="body-copy">From the route into town to the road home, your vehicle works hard. Shree Sanwaliya keeps the care conversation straightforward for local cars, SUVs, and pickups at Motipura, Bundi.</p><Link className="text-link" href="/visit"><span>Find the workshop</span><ArrowUpRight size={16} /></Link></div><div className="home-india-card"><img src={assets.mechanical} alt="Founder working beside a utility pickup in an Indian workshop" /><div><span>Cars + pickups</span><strong>Practical care<br />for the next drive.</strong></div></div></div></section>

    <section className="home-location"><div className="shell-width home-location-grid"><div className="home-location-copy"><SectionLabel number="06" eyebrow="Find the workshop" /><h2>Come to the<br /><span>service bay.</span></h2><p className="body-copy">Use the map to find Shree Sanwaliya at the verified Motipura, Bundi location. Call, message, or open directions before you arrive.</p><div className="home-location-address"><span><MapPin size={17} /></span><div><small>Workshop address</small><strong>{address}</strong></div></div><div className="home-location-actions"><a className="button button--gold" href={mapUrl} target="_blank" rel="noreferrer">Open Google Maps <ArrowUpRight size={16} /></a><Link className="button button--outline" href="/visit">Visit us <ArrowUpRight size={16} /></Link></div></div><div className="home-location-card"><div className="home-location-card-top"><span>Google Maps · Bundi</span><MapPin size={21} /></div><div className="home-location-map"><MapView className="home-map-embed" initialCenter={location} initialZoom={15} fallbackUrl={mapEmbedUrl} /></div><div className="home-location-card-bottom"><span>SH34/SH37A · Motipura</span><a href={mapUrl} target="_blank" rel="noreferrer">Directions <ArrowUpRight size={15} /></a></div></div></div></section>

    <section className="home-contact"><div className="shell-width home-contact-inner"><div><SectionLabel number="07" eyebrow="Find the bay" /><h2>Bring it in.<br /><em>We’ll handle the details.</em></h2><p>Call ahead, send a WhatsApp note, or use the appointment form for car detailing, washing, polishing, light work, rubbing, and broader workshop support.</p><div className="home-contact-actions"><a className="button button--gold" href={`tel:${phone}`}>Call now <PhoneCall size={16} /></a><Link className="button button--outline" href="/visit#appointment"><MessageCircle size={16} /> Book on WhatsApp</Link></div></div><div className="home-contact-card"><ShieldCheck size={22} /><small>Direct workshop line</small><strong>{phone}</strong><a className="text-link" href="/visit#appointment"><span>Open appointment form</span><ArrowUpRight size={16} /></a></div></div></section>
    <CalloutStrip title="Your next clean start is one call away." />
  </div>;
}
