/*
 * Style reminder: the Visit page is a mobile-first conversion page—phone first,
 * directions second, address legible, and no unconfirmed opening-hour copy.
 */
import { ArrowUpRight, CarFront, MapPin, PhoneCall } from "lucide-react";
import { Breadcrumb, PageIntro, SectionLabel } from "@/components/SiteChrome";
import { address, assets, mapUrl, phone } from "@/lib/siteData";

export default function Visit() {
  return <div className="page-shell"><PageIntro number="03" eyebrow="Find the workshop" title="Your next" accent="clean start." lead="Call the team or use directions to find Shree Sanwaliya before the HP Petrol Pump on Main Neemkathana Road, Dadi, Rajasthan." image={assets.hero} /><section className="content-section visit-page-section"><div className="shell-width"><Breadcrumb label="Visit us" /><div className="visit-page-grid"><div className="visit-page-copy"><SectionLabel number="01" eyebrow="Workshop location" /><h2>Come to the<br /><em>service bay.</em></h2><p className="detail-lead">Bring your car or pickup for the service route that fits its next need.</p><div className="address-block"><div className="address-icon"><MapPin size={20} /></div><div><small>Address</small><strong>{address}</strong></div></div><div className="visit-phone-block"><div className="address-icon"><PhoneCall size={20} /></div><div><small>Phone</small><a href={`tel:${phone}`}><strong>{phone}</strong></a></div></div><div className="visit-page-actions"><a href={`tel:${phone}`} className="button button--gold">Call the workshop <PhoneCall size={16} /></a><a href={mapUrl} target="_blank" rel="noreferrer" className="button button--outline">Open directions <ArrowUpRight size={16} /></a></div></div><div className="location-card"><div className="location-card-glow" /><div className="location-card-top"><span>Route marker</span><CarFront size={23} /></div><div className="location-card-map"><div className="map-road map-road--one" /><div className="map-road map-road--two" /><div className="map-pin"><MapPin size={22} /></div><span className="map-label">Dadi / Rajasthan</span></div><div className="location-card-bottom"><span>Before HP Petrol Pump</span><a href={mapUrl} target="_blank" rel="noreferrer">Directions <ArrowUpRight size={15} /></a></div></div></div></div></section><section className="content-section arrival-section"><div className="shell-width arrival-grid"><div><SectionLabel number="02" eyebrow="Before you arrive" /><h2>A little context<br /><span>helps the bay.</span></h2></div><div className="arrival-list"><div><span>01</span><h3>Tell us the vehicle</h3><p>Car, SUV, or pickup—share what you’re bringing when you call.</p></div><div><span>02</span><h3>Tell us the need</h3><p>Washing, interior cleaning, polish, detailing, or a mechanical concern.</p></div><div><span>03</span><h3>Confirm the next step</h3><p>Discuss the service route directly before work begins.</p></div></div></div></section></div>;
}
